#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import mysql from "mysql2/promise";

const ROOT=process.cwd();
const TABLE="tara_ai_providers";
const EXPECTED_COLUMNS=["id","tenant_key","provider","enabled","is_primary","fallback_priority","api_key_encrypted","base_url","model","last_test_status","last_test_message","last_test_at","updated_by","created_at","updated_at"];
const EXPECTED_INDEXES={
  PRIMARY:{unique:true,columns:["id"]},
  uq_tara_ai_providers_tenant_provider:{unique:true,columns:["tenant_key","provider"]},
  idx_tara_ai_providers_order:{unique:false,columns:["tenant_key","enabled","is_primary","fallback_priority"]},
};
function line(k,v){console.log(`${k}=${String(v??"").replace(/[\r\n\t]+/g," ").trim()}`)}
function section(s){console.log(`\n=== ${s} ===`)}
function loadEnv(fp){if(!fs.existsSync(fp))return;for(const raw of fs.readFileSync(fp,"utf8").split(/\r?\n/)){const s=raw.trim();if(!s||s.startsWith("#"))continue;const i=s.indexOf("=");if(i<=0)continue;const k=s.slice(0,i).trim();let v=s.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(!process.env[k])process.env[k]=v;}}
function loadPm2Db(){if(process.env.DATABASE_URL)return;try{const a=JSON.parse(execFileSync("pm2",["jlist"],{encoding:"utf8",stdio:["ignore","pipe","ignore"],maxBuffer:8e6}));const p=a.find(x=>String(x?.pm2_env?.pm_cwd||"")==ROOT)||a.find(x=>String(x?.pm2_env?.pm_cwd||"")=="/var/www/TFCRM")||a.find(x=>/tfcrm/i.test(String(x?.name||"")));const v=p?.pm2_env?.env?.DATABASE_URL||p?.pm2_env?.DATABASE_URL;if(v)process.env.DATABASE_URL=String(v);}catch{}}
function cfg(){const raw=String(process.env.DATABASE_URL||"").trim();if(raw){const u=new URL(raw);return{host:u.hostname,port:Number(u.port||3306),user:decodeURIComponent(u.username),password:decodeURIComponent(u.password),database:u.pathname.replace(/^\//,""),multipleStatements:false}}const c={host:process.env.DB_HOST||"127.0.0.1",port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||"",password:process.env.DB_PASSWORD||"",database:process.env.DB_NAME||"",multipleStatements:false};if(!c.user||!c.database)throw new Error("DB config unavailable");return c;}
function sx(cmd,args){try{return execFileSync(cmd,args,{cwd:ROOT,encoding:"utf8",stdio:["ignore","pipe","ignore"],maxBuffer:8e6}).trim()}catch(e){return String(e?.stdout||"").trim()}}
function idxMap(rows){const m=new Map();for(const r of rows){const n=String(r.indexName);const x=m.get(n)||{unique:Number(r.nonUnique)===0,columns:[]};x.colums.push(String(r.columnName));m.set(n,x)}return m}
async function main(){
console.log("TFCRM_TARA_AI_PROVIDERS_SCHEMA_DIAGNOSTIC_V1");line("READ_ONLY","YES");line("SOURCE_WRITES",0);line("DB_WRITES",0);
section("SOURCE");line("TFCRM_GIT_HEAD",sx("git",["rev-parse","--short=12","HEAD"])||"UNKNOWN");line("WORKTREE_DIRTY",sx("git",["status","--porcelain"])?"YES":"NO");
const sn=sx("grep",["-n","-A","40","-B","4",'export const taraAiProviders = mysqlTable("tara_ai_providers"',"drizzle/schema.ts"]);line("SCHEMA_DEFINITION_FOUND",sn?"YES":"NO");if(sn){console.log("SCHEMA_DEFINITION_BEGIN");console.log(sn);console.log("SCHEMA_DEFINITION_END")}
const rr=sx("grep",["-RIl","--exclude-dir=node_modules","--exclude-dir=.git",TABLE,"drizzle","server","scripts"]);const refs=rr.split(/\r?\n/).filter(Boolean).slice(0,80);line("TABLE_REFERENCE_FILES_COUNT",refs.length);for(const r of refs
console.log(`TABLE_REFERENCE_FILE=${r}`);
section("DATABASE");loadEnv(path.join(ROOT,".env"));loadPm2Db();const c=cfg();const dbName=c.database;const conn=await mysql.createConnection(c);try{await conn.query("SET SESSION TRANSACTION READ ONLY");await conn.query("START TRANSACTION READ ONLY");line("DB_CONNECTION","PASS");line("DB_NAME","[REDACTED]");
const [t]=await conn.query("SELECT TABLE_NAME tableName,ENGINE engine,TABLE_COLLATION tableCollation FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_NAME=?",[dbName,TABLE]);line("TABLE_EXISTS",t.length?"YES":"NO");if(!t.length){line("DIAGNOSIS_HINT","TABLE_MISSING");await conn.query("ROLLBACK");return}
line("TABLE_ENGINE",t[0].engine||"UNKNOWN");line("TABLE_COLLATION",t[0].tableCollation||"UNKNOWN");
const [cols]=await conn.query("SELECT COLUMN_NAME name,DATA_TYPE dataType,COLUMN_TYPE columnType,IS_NULLABLE nullable,CHARACTER_MAXIMUM_LENGTH maxLength,COLUMN_DEFAULT defaultValue,EXTRA extra,ORDINAL_POSITION ordinalPosition FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? ORDER BY ORDINAL_POSITION",[dbName,TABLE]);const names=cols.map(r=>String(r.name));line("ACTUAL_COLUMNS",names.join(",")||"NONE");const missing=EXPECTED_COLUMNS.filter(n=>!names.includes(n));const unexpected=names.filter(n=>!EXPECTED_COLUMNS.includes(n));line("MISSING_COLUMNS",missing.length?missing.join(","):"NONE");line("UNEXPECTED_COLUMNS",unexpected.length?unexpected.join(","):"NONE");for(const r of cols)console.log(`ACTUAL_COLUMN=${r.name}|${r.columnType}|nullable:${r.nullable}|default:${r.name==="api_key_encrypted"?"[REDACTED]":String(r.defaultValue??"NULL")}|extra:${r.extra||""}`);
const [ixr]=await conn.query("SELECT INDEX_NAME indexName,NON_UNIQUE nonUnique,SEQ_IN_INDEX seqInIndex,COLUMN_NAME columnName FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? ORDER BY INDEX_NAME,SEQ_IN_INDEX",[dbName,TABLE]);const im=idxMap(ixr);for(const [n,x] of im)console.log(`ACTUAL_INDEX=${n||unique:${x.unique?"YES":"NO"}|${x.columns.join(",")}`);const issues=[];for(const [n,e] of Object.entries(EXPECTED_INDEXES)){const a=im.get(n);if(!a)issues.push(`MISSING:${n}`);else{if(a.unique!==e.unique)issues.push(`UNIQUE_MISMATCH:${n}`);if(JSON.stringify(a.columns)!==JSON.stringify(e.columns))issues.push(`COLUMNS_MISMATCH:${n}`)}}for(const n of im.keys())if(!EXPECTED_INDEXES[n])issues.push(`UNEXPECTED:${n}`);line("INDEX_ISSUES",issues.length?issues.join("||"):"NONE");
const [cr]=await conn.query(`SELECT COUNT(*) rowCount FROM \`${TABLE}\``);line("ROW_COUNT",Number(cr?.[0]?.rowCount||0));
const safe=["id","tenant_key","provider","enabled","is_primary","fallback_ppriority","base_url","model","last_test_status","last_test_message","last_test_at","updated_by","created_at","updated_at"].filter(x=>names.includes(x));if(safe.length){const [rows]=await conn.query(`SELECT ${safe.map(x=>`\`${x}\``).join(",")} FROM \`${TABLE}\` LIMIT 50`);line("SAFE_ROW_SAMPLE_COUNT",rows.length);for(const row of rows)console.log(`SAFE_ROW=${JSON.stringify(row)}`)}
if(EXPECTED_COLUMNS.every(x=>names.includes(x))){try{await conn.query(`SELECT \`id\`,\`tenant_key\`,\`provider\`,\`enabled\`,\`is_primary\`,\`fallback_priority\`,\`api_key_encrypted\`,\`base_url\`,\`model\`,\`last_test_status\`,\`last_test_message\`,\`last_test_at\`,\`updated_by\`,\`created_at\`,\`updated_at\` FROM \`${TABLE}\` WHERE \`tenant_key\`=? LIMIT 20`,["tfcrm"]);line("CURRENT_SOURCE_SELECT_SMOKE","PASS")}catch(e){line("CURRENT_SOURCE_SELECT_SMOKE",`FAIL:${e.code||"ERROR"}:${e.message}`)}}else line("CURRENT_SOURCE_SELECT_SMOKE","SKIPPED_MISSING_COLUMNS");
let hint="SCHEMA_DRIFT";if(missing.length)hint=`MISSING_COLUMNS:${missing.join(",")}`;else if(issues.length)hint="INDEX_DRIFT";else if(JSON.stringify(names)===JSON.stringify(EXPECTED_COLUMNS))hint="COLUMN_NAMES_MATCH_SOURCE_CHECK_DEFINITIONS_OR_RUNTIME_INSERT";line("DIAGNOSIS_HINT",hint);await conn.query("ROLLBACK");}finally{try{await conn.end()}catch{}}
section("SAFETY");line("DB_SCHEMA_CHANGED","NO");line("DB_DATA_CHANGED","NO");line("TFCRM_SOURCE_CHANGED","NO");line("PM2_RESTARTED","NO");line("DOCKER_TOUCHED","NO");line("PROVIDER_API_CALLED","NO");console.log("\nEND_TFCRM_TARA_AI_PROVIDERS_SCHEMA_DIAGNOSTIC_V1");}
main().catch(e=>{line("FATAL",`${e?.code||"ERROR"}:${String(e?.message||e).replace(/[\r\n]+/g," ").slice(0,800)}`);process.exitCode=1});
